name: CS102 Workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.5'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black mypy pylint pygame pyfakefs
    - name: Run black
      run: |
        black -l 100 homework01/caesar.py homework01/vigenere.py homework01/rsa.py
    - name: Run isort
      run: |
        isort homework01/caesar.py homework01/vigenere.py homework01/rsa.py
    - name: Run mypy
      run: |
       mypy homework01/caesar.py homework01/vigenere.py homework01/rsa.py --ignore-missing
    - name: Run pylint
      run: |
        pylint --exit-zero homework01/caesar.py homework01/vigenere.py homework01/rsa.py
    - name: Run unittests
      run: |
        python -m unittest discover homework01/caesar.py homework01/vigenere.py homework01/rsa.py
