name: CS102 Workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.5'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black mypy pylint pygame pyfakefs
        pip install -r homework01/requirements.txt
    - name: Run black
      run: |
        black -l 100 caesar.py vigenere.py rsa.py
    - name: Run isort
      run: |
        isort caesar.py vigenere.py rsa.py
    - name: Run mypy
      run: |
       mypy caesar.py vigenere.py rsa.py --ignore-missing
    - name: Run pylint
      run: |
        pylint --exit-zero ${{ github.head_ref }}
    - name: Run unittests
      run: |
        python -m unittest discover ${{ github.head_ref }}
